query foods {
  getFoods {
    _id
    category
    description
    image
    name
    discount
  }
}

query Orders($token: String ) {
  getOrder(token: $token) {
    discount
    items {
      customeName
      productId
    }
    status
    total
  }
}
query orderId($token: String , $id: String ) {
  getOrderById(id: $id, token: $token) {
    discount
    items {
      customeName
      dips {
        name
        price
        quantity
      }
      extras {
        name
        quantity
        price
      }
      productId
      price
      quantity
      sauces {
        name
        price
        quantity
      }
      shopId
      toppings {
        name
        price
        quantity
      }
      userId
    }
    paymentId
    paymentMethod
    shopId
    status
    total
    userId
  }
}