query foods {
 getFoods {
    _id
    category
    description
    status
    foodType
    image
    name
    price
  } 
}

query Orders($token: String ) {
 getOrder(
    token: $token
  ) {
    _id
    createdAt
    customeName
    total
    status
    paymentMethod
  } 
}
query orderId($token: String , $id: String ) {
 getOrderById(id: $id, token: $token) {
    _id
    createdAt
    customeName
    discount
    items {
      _id
      price
      productId
      quantity
      shopId
      userId
      dips {
        name
        price
      }
      extras {
        name
        price
      }
      sauces {
        name
        price
      }
      toppings {
        name
        price
      }
    }
    paymentId
    paymentMethod
    shopId
    status
    total
    userId
  } 
}