name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 6.0.2

    - name: Install dependencies
      run: pnpm install 

    - name: Build
      run: pnpm run build

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    # - name: Deploy
    #   run: |
    #     git config --global user.name $user_name
    #     git config --global user.email $user_email
    #     git remote set-url origin https://${github_token}@github.com/${repository}
    #     pnpm run deploy
    #   env:
    #     user_name: 'prashantm2001'
    #     user_email: 'prashant.om@somaiya.edu'
    #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
    #     repository: ${{ github.repository }}